= Bandit Solutions

// asciidoc supports comments :)


== Level 0

Here, we will be using `ssh` command to login remotely into the server. The syntax of the command is `ssh username@server.ip -p port`

`$ ssh bandit0@bandit.labs.overthewire.org -p 2220` +
and enter password `bandit0`


== Level 0 -> 1

In *nix systems, `ls` command can be used to list all non-hidden files in the current working directory. We will use this to get the list of all files here and then use `cat` commant to show their contents.

`$ ssh bandit0@bandit.labs.overthewire.org -p 2220` +
`bandit0@bandit:~$ ls` +
`readme` +
`bandit0@bandit:~$ cat readme` +
`[password redacted]`
// NH2SXQwcBdpmTEzi3bvBHMM9H66vVXjL


== Level 1 -> 2

Here, the filename is `-`. This character present in the filename creates an ambiguity as if it is a argument flag to the command `cat` when `cat -` is used. Also in some *nix commands, `-` is used as an "interactive input" flag, which also results in an ambiguity. To solve this issue, we will use the relative full path for the file: `./-`  which specifies that `-` is a file in the current directory and not an argument to the command.

`$ ssh bandit1@bandit.labs.overthewire.org -p 2220` +
`bandit1@bandit:~$ ls` +
`-` +
`bandit1@bandit:~$ cat ./-` +
`[password redacted]`
// rRGizSaX8Mk1RTb1CNQoXTcYZWU6lgzi


== Level 2 -> 3

If files have multiple spaces in their name, we have to "quote" them.

`$ ssh bandit2@bandit.labs.overthewire.org -p 2220` +
`bandit2@bandit:~$ ls` +
`spaces in this filename` +
`bandit2@bandit:~$ cat "spaces in this filename"` +
`[password redacted]`
// aBZ0W5EmUfAf7kHTQeOwd8bauFJ2lAiG

P.S. if files have "quotes" in their names, we have to "quote \" unquote" them. Here, `\"` specifies that the file has a quote in its name.


== Level 3 -> 4

Since the file is a hidden file, we can easily find it by using the `-la` flag with the `ls` command. `a` refers to `all` and `A` is also the same as all but it doesn't show the obvious `.` and `..` directories.

`$ ssh bandit3@bandit.labs.overthewire.org -p 2220` +
`bandit3@bandit:~$ ls -l` +
`total 4` +
`drwxr-xr-x 2 root root 4096 Oct  5 06:19 inhere` +
we can see that there is a directory named `inhere` in here +
`bandit3@bandit:~$ cd inhere` +
`bandit3@bandit:~/inhere$ ls -lA` +
`total 4` +
`-rw-r----- 1 bandit4 bandit3 33 Oct  5 06:19 .hidden` +
`bandit3@bandit:~/inhere$ cat .hidden` +
`[password redacted]`
// 2EW7BBsr6aMMoJ2HjW067dm8EgX26xNe


== Level 4 -> 5

Theres is a handy utility, the `file` command, which lets us identify the file type of the file we supply it. We will be using the wildcard pattern `\*` here, since the number of files are very less and then see the output of each file. `\*` just means all in layman terms. We used `./*` to say, "all files in this directory".

`$ ssh bandit4@bandit.labs.overthewire.org -p 2220` +
`bandit4@bandit:~$ ls` +
`inhere` +
`bandit4@bandit:~$ cd inhere` +
`bandit4@bandit:~/inhere$ ls` +
`-file00  -file01  -file02  -file03  -file04  -file05  -file06  -file07  -file08  -file09` +
`bandit4@bandit:~/inhere$ file ./*` +
`./-file00: data` +
`./-file01: data` +
`./-file02: data` +
`./-file03: data` +
`./-file04: data` +
`./-file05: data` +
`./-file06: data` +
`./-file07: ASCII text` +
`./-file08: data` +
`./-file09: data` +
`bandit4@bandit:~/inhere$ cat ./-file07` +
`[password redacted]`
// lrIWWI6bB37kxfiCQZqUdOIYfr6eEeqR


== Level 5 -> 6

Since there are multiple directories here, we will use the `find` command to filter out the exact file we want to find. +
`find <location> conditions` +
Here, `-size 1033c` means that it is `1033` characters in size or 1033 bytes. `! executable` means that it should not be an executable binary file.

`$ ssh bandit5@bandit.labs.overthewire.org -p 2220` +
`bandit5@bandit:~$ ls` +
`inhere` +
`bandit5@bandit:~$ cd inhere` +
`bandit5@bandit:~/inhere$ ls -l` +
`total 80` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere00` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere01` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere02` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere03` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere04` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere05` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere06` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere07` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere08` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere09` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere10` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere11` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere12` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere13` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere14` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere15` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere16` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere17` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere18` +
`drwxr-x--- 2 root bandit5 4096 Oct  5 06:19 maybehere19` +
`bandit5@bandit:~/inhere$ find . -size 1033c ! -executable` +
`./maybehere07/.file2` +
`bandit5@bandit:~/inhere$ cat ./maybehere07/.file2` +
`[password redacted]`
// P4L4vucdmLnm8I7Vl7jG1ApGSfjYKqJU


== Level 6 -> 7

We'll be using the same `find` command we learned in the previous challenge here. We just have more conditions to apply to filter out the password file.

`-size 33c` -> size should be 33 bytes +
`-user bandit7` -> file should be owned by user `bandit7` +
`-group bandit6` -> file should be owned by the group `bandit6`

From now on, I'll assume that we have already logged in to the server and got the shell.

`$ cd /` +
`$ find . -size 33c -user bandit7 -group bandit6` +
`[\...]` +
`./var/lib/dpkg/info/bandit7.password` +
`[\...]` +
`$ cat ./var/lib/dpkg/info/bandit7.password` +
`[password redacted]`
// z7WtoNQU2XfjmMtWA8u5rN4vzqu4v99S


== Level 7 -> 8

`less` is another very helpful command which let's us analyse a fewer lines of the output at a time if the output is very large. It follows `vi` style keybindings, so we can search for the exact phrase in the output of `cat`.

`$ cat data.txt | less` +
Using standard vi style searching, search the word 'millionth' as `/millionth` and press enter. +
`[\...]` +
`huffy   WJDdimZChuTlmWvX1f00KQgSd3DI63in` +
`millionth       [password redacted]` +
`Roderick's      zbqXMhsLoFPqc2Mf0TJwI7H6KXp75PSi` +
`[\...]`
// TESKZC0XvTetK0S9xNwm25STk5iWrBvP


== Level 8 -> 9

`$ python3` +
`>>> lines = {}` +
`>>> with open('data.txt', 'r') as file:` +
`\... while line := file.readline():` +
`\...  \... if not line in lines:` +
`\...  \... \... lines[line] = 1` +
`\... \... else:` +
`\... \... \... lines[line] += 1` +
`\...` +
`>>> for k,v in lines.items():` +
`\... \... if v == 1:` +
`\... \... \... print(k)` +
`\... \... \... exit(0)` +
`[password redacted]`
// EN632PlfYiZbn3PhVK3XOGSlNInNE00t


== Level 9 -> 10

`$ strings data.txt | grep == `
`x]T========== theG)"` +
`========== passwordk^` +
`========== is` +
`========== [password redacted]` +
// G7w8LIi6J3kTb8A7j9LgrywtEUlyyp6s


== Level 10 -> 11

`$ cat data.txt | base64 -d` +
`The password is [password redacted ]` +
// 6zPeziLdR2RKNdNYFNb6nVCKzphlXHBM


== Level 11 -> 12

`$ cat data.txt | tr 'A-Za-z' 'N-ZA-Mn-za-m'` +
(x + 13) mod 26 + 
`The password is [password redacted]`
// JVNBBFSmZwKKOP0XbFXOoW8chDz5yVRv


== Level 12 -> 13

`$ mkdir /tmp/krishna2803` +
`$ cd /tmp/krishna2803` + 
`$ cp ~/data.txt .` + 
To reverse the hexdump, we will use `xxd -r` +

`$ xxd -r data.txt data` +
`$ file data` +
`data: gzip compressed data, was "data2.bin", last modified: Thu Oct  5 06:19:20 2023, max compression, from Unix, original size modulo 2^32 573` +
This is a `gz` file. +
`$ mv data data.gz && gzip -d data.gz` +
`$ file data` +
`data: bzip2 compressed data, block size = 900k` +
`$ bzip2 -d data` +
`bzip2: Can't guess original name for data -- using data.out` +
`$ file data.out` +
`data.out: gzip compressed data, was "data4.bin", last modified: Thu Oct  5 06:19:20 2023, max compression, from Unix, original size modulo 2^32 20480` +
`$ mv data.out data.gz && gzip -d data.gz` +
`$ ls` +
`data data.txt` + 
`$ file data` + 
`data: POSIX tar archive (GNU)` +
`$ tar xvf data` + 
Followed by a series of `tar xvf` and `gzip -d`, we get: +
`The password is [password redacted]` +
in a ASCII Plaintext file
// wbWdlBxEir4CaE8LaPhauuOo6pwRmrDw


== Level 13 -> 14

`$ ls` +
`sshkey.private` +
`$ cat sshkey.private` +
`-----BEGIN RSA PRIVATE KEY-----` +
`[\...]` +
`-----END RSA PRIVATE KEY-----` +
Copy this key and login to `bandit14` using this key. Remember to change the permissions to 700 +
`$ ssh -i key bandit14@bandit.labs.overthewire.org -p 2220` 


== Level 14 -> 15

Using hints from the previous level. +
`$ cat /etc/bandit_pass/bandit14` +
`[password redacted]` +
// fGrHPx402xGC7U7rXKDaxiWFTOiF0ENq
`$ nc 127.0.0.1 30000` +
Submit the password for the current level +
`Correct!` + 
`[password redacted]`
// jN2kgmIXJ6fShzhT2avhotn4Zcka6tnt


== Level 15 -> 16

https://www.openssl.org/docs/man1.0.2/man1/openssl-s_client.html

`$ openssl s_client -connect 127.0.0.1:30001` +
`Correct!` + 
`[password redacted]`
// JQttfApK4SeyHwDlI9SXGR50qclOAil1


== Level 16 -> 17

`$ nmap -sV 127.0.0.1 -p 31000-32000` +
`31046/tcp open  echo` +
`31518/tcp open  ssl/echo` +
`31691/tcp open  echo` +
`31790/tcp open  ssl/unknown` +
`31960/tcp open  echo` +
`$ openssl s_client -connect 127.0.0.1:31790` +
`Correct!` +
`[RSA KEY]` +

== Level 17 -> 18

`$ diff passwords.old passwords.new` +
`42c42` +
`< p6ggwdNHncnmCNxuAt0KtKVq185ZU7AW` +
`---` +
`> [password redacted]` +
// hga5tuuCLF6fFzUpnagiMN8ssu9LFrdg


== Level 18 -> 19

`$ ssh bandit18@bandit.labs.overthewire.org -p 2220 "cat *"` +
`[password redacted]`+
// awhqfNnAbc1naukrpqDYcF95h7HoMTrC


== Level 19 -> 20


`$ ./bandit20-do cat /etc/bandit_pass/bandit20` +
`[password redacted]` +
// VxCazJaVykI6W36BkBU0mJTCM8rR95XT


== Level 20 -> 21

Just let the thing run in the background by forking the process:

`$ echo "[current password]" | nc -l -p 6969 & disown` +
`$ ./suconnect 6969` +
`Read: [current password]` +
`Password matches, sending next password` +
`[password redacted]` +
// NvEJF7oVjkddltPSrdKEFOllh9V1IBcq

